name: Release

on:
  repository_dispatch:
    types:
      - trigger-release
  # workflow_run:
  #   workflows: [test-workflow]
  #   types:
  #     - completed

jobs:
  release:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Debug Workflow Run
        run: |
          echo "Workflow ${{ github.workflow }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "Workflow Run Ref: ${{ github.ref }}"
          echo "Workflow Run Base Ref: ${{ github.base_ref }}"
          echo "Workflow Run Repositoy: ${{ github.repository }}"
          echo "Workflow Run Event: ${{ github.event }}"
          echo "Workflow Run Event Name: ${{ github.event_name }}"

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
