name: Release

on:
  push:
    branches:
      - alpha
  # workflow_run:
  #   workflows: [trigger-release]
  #   types:
  #     - completed
  # repository_dispatch:
  #   types:
  #     - trigger-release

jobs:
  release:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug Workflow Run
        run: |
          echo "Workflow ${{ github.workflow }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "Workflow Run Ref: ${{ github.ref }}"
          echo "Workflow Run Base Ref: ${{ github.base_ref }}"
          echo "Workflow Run Repositoy: ${{ github.repository }}"
          echo "Workflow Run Event: ${{ github.event }}"
          echo "Workflow Run Event Name: ${{ github.event_name }}"

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Run Test Workflow
        id: test_workflow
        uses: ./.github/workflows/test-workflow.yml

      - name: Handle Test Workflow Result
        if: steps.test_workflow.outputs.result == 'success'
        run: |
          npm ci
          npx semantic-release
          echo "Test Workflow succeeded"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle Test Workflow Failure
        if: steps.test_workflow.outputs.result != 'success'
        run: |
          echo "Test Workflow failed"
          exit 1
