name: Release Workflow

on:
  workflow_dispatch:

jobs:
  release_job:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Test Workflow
        uses: ./.github/workflows/test-workflow.yml

  continue_job:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    needs: release_job
    if: ${{ needs.release_job.result == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Debug Workflow Run
        run: |
          echo "Workflow ${{ github.workflow }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "Workflow Run Ref: ${{ github.ref }}"
          echo "Workflow Run Base Ref: ${{ github.base_ref }}"
          echo "Workflow Run Repositoy: ${{ github.repository }}"
          echo "Workflow Run Event: ${{ github.event }}"
          echo "Workflow Run Event Name: ${{ github.event_name }}"

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
