name: Test Workflow

on:
  workflow_call:

jobs:
  test-workflow:
    name: Test Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Debug Workflow Run
        run: |
          echo "Workflow ${{ github.workflow }}"
          echo "Workflow Run ID: ${{ github.run_id }}"
          echo "Workflow Run Ref: ${{ github.ref }}"
          echo "Workflow Run Base Ref: ${{ github.base_ref }}"
          echo "Workflow Run Repositoy: ${{ github.repository }}"
          echo "Workflow Run Event: ${{ github.event }}"
          echo "Workflow Run Event Name: ${{ github.event_name }}"

      - name: Check out repository
        uses: actions/checkout@v3

      - run: |
          echo "Workflow Run ActionStatus: ${{ job.status }}."

      - name: Set Test Result
        id: set_result
        run: |
          if [ $? -eq 0 ]; then
            echo "::set-output name=result::success"
          else
            echo "::set-output name=result::failure"
          fi

  # trigger-release:
  #   name: Trigger Release Workflow
  #   permissions:
  #     contents: write
  #   needs: test-workflow
  #   if: ${{ needs.test-workflow.result == 'success' }}

  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger Release Workflow
  #       uses: peter-evans/repository-dispatch@v2
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         repository: ${{ github.repository }}
  #         event-type: release.yml

  # - name: Trigger Release Workflow
  #   if: ${{ success() }}
  #   uses: peter-evans/repository-dispatch@v2
  #   with:
  #     token: ${{ secrets.GITHUB_TOKEN }}
  #     repository: ${{ github.repository }}
  #     event-type: release.yml
