name: CI B

on:
  push:
    branches:
      - alpha

jobs:
  ci-b-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Adicione aqui os passos necessários para executar o fluxo de trabalho de CI 'B'

  notify-a-job:
    needs: ci-b-job
    if: ${{ needs.ci-b-job.result == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Notify CI A
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: workflow-done

      - run: echo "Workflow B bem-sucedido!"

  # trigger-release:
  #   name: Trigger Release Workflow
  #   permissions:
  #     contents: write
  #   needs: test-workflow
  #   if: ${{ needs.test-workflow.result == 'success' }}

  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Trigger Release Workflow
  #       uses: peter-evans/repository-dispatch@v2
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         repository: ${{ github.repository }}
  #         event-type: release.yml
